version: "3.8"
services:
   db:
    image: mahesaj/db-lantickku:v1
    container_name: db-landtick
    ports:
      - 5432:5432
    volumes:
      - ~/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
   backend:
    depends_on:
      - db
    image: mahesaj/be-lantickku:v5
    container_name: be-landtick
    stdin_open: true
    restart: unless-stopped
    ports:
      - 5000:5000
   frontend:
    image: mahesaj/fe-lanttickku:v1
    container_name: fe-landtick
    stdin_open: true
    restart: unless-stopped
    ports:
      - 5173:5173
